aurball: Allow specifying what file is the PKGBUILD

diff --git a/bin/aurball b/bin/aurball
--- a/bin/aurball
+++ b/bin/aurball
@@ -1,6 +1,18 @@
 #!/bin/bash
 
 set -e
-makepkg --source
-srcname=$(. PKGBUILD; echo "$pkgname-$pkgver-$pkgrel.src.tar.gz")
+
+script=PKGBUILD
+
+if [[ -n $1 ]]; then
+    script=$1
+fi
+
+if [[ ! -r $1 ]]; then
+    echo "Can't read $1!"
+    exit 1
+fi
+
+makepkg --source -p $script
+srcname=$(. $script; echo "$pkgname-$pkgver-$pkgrel.src.tar.gz")
 burp $srcname
